// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class INSERT_SUBJECT : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(INSERT_SUBJECT));
        
        string IMigrationMetadata.Id
        {
            get { return "202110161315490_INSERT_SUBJECT"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
