// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class INSERT_CLASS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(INSERT_CLASS));
        
        string IMigrationMetadata.Id
        {
            get { return "202110161314130_INSERT_CLASS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
