// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class INSERT_TEACHER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(INSERT_TEACHER));
        
        string IMigrationMetadata.Id
        {
            get { return "202110161317105_INSERT_TEACHER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
